# GIS 712, 2024: Environmental Earth Observation and Remote Sensing  
## Introduction to Python data types and structures

Data is commonly organized and stored in structures so that they can be accessed and manipulated more efficiently. These structures define the different relationship between the data and the possible operations that can be performed.   

![](data/image.png)

### A quick recap on how to create a conda environment using a YAML file.  

Open the Anaconda Prompt (PC users)/Terminal (Mac users) and navigate to the directory where the files for intro_python.ipynb and GIS712.yml are located. Then run the commands below:

```
# to check your envs
conda info --envs

# to create a new one
conda env create --file = GIS712.YAML

# to activate the new env
conda activate GIS712

```

## Primitive Data types
### Integers  
Represented by int() class. It is a positive or negative whole number. In python there is no limit on how long the integer can be. 


In [14]:
# interger example
a = 8
b = 7

# print messages
print("Type of a: ", type(a)) 

# operations
c = a + b
print("Sum of a and b is: ", c)

# Subtraction
difference = a - b
print("Difference:", difference)

# Multiplication
product = a * b
print("Product:", product)

# Division
quotient = a / b
print("Quotient:", quotient)

# Modulus
remainder = a % b
print("Remainder:", remainder)

# Exponentiation
power = a ** b
print("Power:", power)

Type of a:  <class 'int'>
Sum of a and b is:  15
Difference: 1
Product: 56
Quotient: 1.1428571428571428
Remainder: 1
Power: 2097152


### Floats  
Represented by float() class. It is a real number with floating point representation. 

In [15]:
# pi is a float!
pi = 3.14159265359
print(pi)
print(type(pi))

3.14159265359
<class 'float'>


### Strings  
Represented by str() class. Strings are defined by apostrophes or quotation marks, and they are indexed and in sequence.



In [16]:
string = 'Remote sensing is art!' 
string2 = "And Earth observation is exciting"
print(string)

# indexing to print different parts of the string
print(string[0:5],string[10:15])

# add both strings
print(string + ' ' + string2 + '.')

### OLDER STYLE
# using .format method to customize messages
print('string: {0} and string2: {1}'.format(string, string2))

### NEWER STYLE
# using f-string method to customize messages
print(f'string: {string} and string2: {string2}')

print(f'{string}, hello')

Remote sensing is art!
Remot sing 
Remote sensing is art! And Earth observation is exciting.
string: Remote sensing is art! and string2: And Earth observation is exciting
string: Remote sensing is art! and string2: And Earth observation is exciting
Remote sensing is art!, hello


In [17]:
# What happens when we want to add an integer to a string?
var1 = 25
var2 = '3'

print(var1 + var2)

TypeError: unsupported operand type(s) for +: 'int' and 'str'

We got an error! Error messages can be very helpful for debugging code. The first thing to look for is what kind of error we got. In this case, it is a `TypeError`. 

Why do you think we got a `TypeError`?

The next thing to look at is the error message, which comes after the error type. In this case, our error message is `unsupported operand type(s) for +: 'int' and 'str'`.

This message is telling us that we cannot use the operand `+` between an integer variable and a string variable. 

How can we fix this error?

In [18]:
print(var1 + int(var2))

28


What happens if we cast `var1` to a string? Try it out!

In [19]:
# ADD YOUR CODE HERE

print(str(var1) + var2)

253


### Booleans  

Data type with one of the two built-in values, **True** or **False**. Booleans are very useful to control the flow of code. For instance, different scenarios can happen if a variable is TRUE or FALSE.

### Boolean logical operators  
**or**:     Will evaluate to **True** if at least one (but not necessarily both) statements are **True**  

**and**:    Will evaluate to **True** only if both statements are **True**  

**not**:    Reverses the result of the statement  

### Boolean comparison operators include:  
equal: `==`  

not equal: `!=`  

greater or equal than: `>=`   

less or equal than: `<=`  

greater than: `>`   

less than: `<`  

In [20]:
# Test for equality
'AAA' == 'BBBx'

False

In [21]:
# show data type
type('AAA' == 'BBBx')

bool

In [22]:
# define str sequence
a = 'AAPT'
b = 89

In [23]:
# AND conditional
a == 'CGC' and a == 'AGU'

False

In [24]:
# OR conditional
a == 'CGC' or a == 'AAPT'

True

In [25]:
# reverse results
not (a == 'CGC') 

True

In [26]:
# Combined AND-OR conditional (evaluated from left to right)

## (FALSE     or  TRUE)
##          TRUE              and    TRUE
(a == 'AGU') or (a == 'AAPT') and (b == 89)

True

Write a Boolean expression using `!=`, `>=`, `<`, `not`, and `or` that yields a **True** Boolean value

In [60]:
#### ADD YOUR CODE HERE

b <= 90

True

## Non-Primitive Data types
### Arrays
Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

Example: np.array(#row, #column).  


In [28]:
# importing numpy
import numpy as np

a = np.zeros((2,2))   # Create an array of all zeros
print('a is \n', a)             

b = np.ones((3,3))    # Create an array of all ones
print('b is \n', b)             

c = np.full((5,2), 28)  # Create a constant array
print('c is \n', c)               

d = np.eye(2)         # Create a 2x2 identity matrix
print('d is \n', d)             

e = np.random.random((3,3))  # Create an array filled with random floats between [0.0, 1.0)
print('e is \n', e)

f = np.random.randint(5, size=(2, 4))  # Generate a 2x4 array of ints between 0 and 5, excluding 5.
print('f is \n', f) 


a is 
 [[0. 0.]
 [0. 0.]]
b is 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
c is 
 [[28 28]
 [28 28]
 [28 28]
 [28 28]
 [28 28]]
d is 
 [[1. 0.]
 [0. 1.]]
e is 
 [[0.06059524 0.13377091 0.60577359]
 [0.2602531  0.94357566 0.91592059]
 [0.46450212 0.40762146 0.5905603 ]]
f is 
 [[2 2 1 1]
 [2 3 3 2]]


#### Slicing: we must specify a slice for each dimension of the array:

In [29]:
# slicing
print(e[0:2,:]) # first two rows

print(e[1:3,0:2]) #first two elements of the 2nd and 3rd rows

print(e[:,:]) # entire array

[[0.06059524 0.13377091 0.60577359]
 [0.2602531  0.94357566 0.91592059]]
[[0.2602531  0.94357566]
 [0.46450212 0.40762146]]
[[0.06059524 0.13377091 0.60577359]
 [0.2602531  0.94357566 0.91592059]
 [0.46450212 0.40762146 0.5905603 ]]


In [61]:
#### ADD YOUR CODE HERE

# Print the 3rd value in the 1st row of array f
print(f[0, 2])
# Print the last value of the last row in array e
print(e[-1, -1])


1
0.590560302021869


### Lists
A list is a collection which is ordered and changeable. Lists are represented by brackets. Lists can be indexed and sliced too!


In [31]:
# list example
lst = ['banana', 'apple', 'grape', 'lime', 'lime']

# print len
print(len(lst))

# access list item
print(lst[0],lst[2])

# Negative indexing means beginning from the end, -1 refers to the last item
print(lst[-1])

# changing list value
lst[2] = 'horse'
print(lst)

# add item to list
lst.append('watermelon sugar')
print(lst)

# remove item from list
lst.remove('horse')
print(lst)

# join two lists
lst2 = ['yellow', 'red', 'purple', 'green']
lst3 = lst + lst2
print(lst3)


5
banana grape
lime
['banana', 'apple', 'horse', 'lime', 'lime']
['banana', 'apple', 'horse', 'lime', 'lime', 'watermelon sugar']
['banana', 'apple', 'lime', 'lime', 'watermelon sugar']
['banana', 'apple', 'lime', 'lime', 'watermelon sugar', 'yellow', 'red', 'purple', 'green']


In [68]:
#### ADD YOUR CODE HERE

# Create a list with 6 elements
list_ = [i for i in range(6)]
print(f"list_: {list_}")

# Print the 5th value in list
print(list_[4])

# Print the last value in the list
print(list_[-1])

# Create another list of 2 elements
list_1 = [i for i in range(6, 8)]
print(f"list_1: {list_1}")

# Add the last element of your first list to your second list
list_1 = [*list_1, list_[-1]]
print(f"list_1: {list_1}")

# Add the first element of the first list to the second place in your second list
list_1[1] = list_[0]
# list_1.insert(1, list_[0])
print(f"list_1: {list_1}")


list_: [0, 1, 2, 3, 4, 5]
4
5
list_1: [6, 7]
list_1: [6, 7, 5]
list_1: [6, 0, 5]


In [69]:
# Create a list with 6 elements
my_list = ['COZY','Run the world','Single Ladies', 'CUFF IT','Halo','ENERGY']

# Print the 5th value in list
print(my_list[4])

# Print the last value in the list
print(my_list[-1])

# Create another list of 2 elements
my_list1 = ['Bills','Beautiful Liar']

# Add the last element of your first list to your second list
# my_list.append(my_list1[-1])
# print(my_list)

my_list1.append(my_list[-1])
print(my_list1)

# Add the first element of the first list to the second place in your second list
my_list1[1] = my_list[0]
print(my_list1)

Halo
ENERGY
['Bills', 'Beautiful Liar', 'ENERGY']
['Bills', 'COZY', 'ENERGY']


### Tuple 
A tuple is a collection which is ordered and unchangeable. In Python tuples are written with parentheses.  
Tuples are unchangeable, so you cannot remove items from them, but you can delete the tuple completely

In [70]:
# example
tpl = ('banana', 'apple', 'grape', 'lime')

# print len
print(len(tpl))

# access items
print(tpl[3]) #lime

# example
tpl2 = ('banana', 'apple','banana','banana','apple','apple','apple','banana','apple','banana','banana','banana','banana', 'grape','grape','grape','grape', 'lime')

# use method count
print(tpl2.count('banana'))
print(tpl2.count('apple'))
print(tpl2.count('lime'))

# index
print(tpl2.index('grape')) # return the index of the first grape in order

4
lime
8
5
1
13


### Set
A set stores a collection of items which is unordered, unchangeable, and unindexed. It **cannot** store duplicates, but it can contain items of different data types. Sets are written with curly brackets, `{}`, and items are separated with commas.

In [71]:
# example
set_ex = {'a', 'b', 3, ('c', 2)}

# print the set
print(f'set_ex: {set_ex}')

# print the length of the set
print(len(set_ex))

# pop first element in the set and see how the set changes
print(f'set_ex: {set_ex}')
popped = set_ex.pop()
print(f'popped: {popped}')
print(f'set_ex: {set_ex}')

set_ex: {'b', 3, ('c', 2), 'a'}
4
set_ex: {'b', 3, ('c', 2), 'a'}
popped: b
set_ex: {3, ('c', 2), 'a'}


### Dictionary
A dictionary is a collection which is unordered, changeable and indexed. In Python dictionaries are written with curly brackets, and they have keys and values.  

The zip() function returns a zip object, which is an iterator of tuples where the first item in each passed iterator is paired together, and then the second item in each passed iterator are paired together etc.

In [36]:
d = {"mollie": "PhD student", "rebecca": "PhD student", "Mirela":"professor", "Julio": "postdoc"}
# Accessing dictionary values
print(d["mollie"])
print(d.get("rebecca"))


# Adding a new key-value pair
d["varun"] = "PhD student"
print(d)


# Looping through dictionary keys and values
for key, value in d.items():
    print(key, ":", value)


# converting lists to dictionary using zips
lst = ['banana', 'apple', 'grape', 'lime']
lst2 = ['yellow', 'red', 'purple', 'green']

dictionary = dict(zip(lst, lst2)) 

print(dictionary)

# checking for individual fruit color
print(dictionary['grape'])




PhD student
PhD student
{'mollie': 'PhD student', 'rebecca': 'PhD student', 'Mirela': 'professor', 'Julio': 'postdoc', 'varun': 'PhD student'}
mollie : PhD student
rebecca : PhD student
Mirela : professor
Julio : postdoc
varun : PhD student
{'banana': 'yellow', 'apple': 'red', 'grape': 'purple', 'lime': 'green'}
purple


In [72]:
#### ADD YOUR CODE HERE

# Create your own dictionary with 4 elements
dict_ = {i: str(i) for i in range(4)}
print(f"dict_: {dict_}")

# Use a key to get a value
key_ = 0
print(f"key: {key_}, val: {dict_[key_]}")

# Add an element to the dictionary
dict_["8"] = 8
print(f"dict_: {dict_}")

dict_: {0: '0', 1: '1', 2: '2', 3: '3'}
key: 0, val: 0
dict_: {0: '0', 1: '1', 2: '2', 3: '3', '8': 8}


## Conditional statements in Python

### indentation:
Python relies on indentation (whitespace at the beginning of a line) to define scope in the code


In [73]:
a = 2500
b = 2352

if b > a:
    print("b is greater than a")
elif b < a: 
    print("b is smaller than a")
elif a == b:
    print('b equals to a')
else:
    print('something is going on!')


if 1 == 2:
    print('hmmm, something is weird')
elif 1 == 1:
    print('Nice!')
else:
    print('what is going on with my code??')
    


b is smaller than a
Nice!


In [74]:
c = 3442

if a > b or a > c:
  print("At least one of the conditions is True")
else:
    print("no statements are true")

At least one of the conditions is True


In [75]:

if a > b and b > c:
    print("Both conditions are True")
else:
    print('at least one of the conditions is not true!')

at least one of the conditions is not true!


In [76]:
#### ADD YOUR CODE HERE

# Write an IF ELSE statment using ==
if c == b:
    print("c == b")
else:
    print("c != b")

# Write an IF ELIF ELSE statement using AND
if c is None and b is not None:
    print("We here")
elif b == 42 and a != 42:
    print("Now here")
else:
    print("Most likely here")

# Write an IF ELIF ELSE statement using 3 Boolean expressions
if (isinstance(c, str) or isinstance(c, int)) and isinstance(b, int):
    print("c is int or string & b is int")
elif b == 3 or b == 4 or b == 5:
    print("b in (3, 4, 5)")
else:
    print("wot")

c != b
Most likely here
c is int or string & b is int


## FOR and WHILE loops in python  
### FOR loop
A for loop is used for iterating over a sequence (that is either a list, a tuple, a dictionary, a set, or a string).

In [77]:
# use our lists
lst = ['banana', 'apple', 'grape', 'lime']
lst2 = ['yellow', 'red', 'purple', 'green']

for i in lst:
    print(i)
    

banana
apple
grape
lime


In [43]:
# print creting a message using two lists and their
ind = range(0,len(lst)) # create a list with items position


# for loop with .format and indexing
# for i in ind:
#     print('{0} is {1}'.format(lst[i],lst2[i]))



In [78]:
# step in python
#ind=range(start,length, step)
for i in range(0,len(ind),2):
    print('{0} is {1}'.format(lst[i],lst2[i]))

banana is yellow
grape is purple


In [79]:
# add conditional to for loops
a = 10
b = 5

# if else
if a > b:
    for i in ind:
        print('{0} is {1}'.format(lst[i],lst2[i]))
else:
    print ('a is smaller than b')

banana is yellow
apple is red
grape is purple
lime is green


In [80]:
# Conditional using operators
for i in lst:
    if i != 'lime':
        print('I love {0} with Nutella'.format(i))
    else:
        print('{0} with Nutella is not that good..'.format(i))

I love banana with Nutella
I love apple with Nutella
I love grape with Nutella
lime with Nutella is not that good..


In [85]:
#### ADD YOUR CODE HERE

print("All 1 - 10:")
# Write a FOR loop to print every number 0-10
for i in range(11):
    print(f"\t{i}")

print("\nEven 1 - 10:")
# Write a FOR loop to print every even number 0-10 (hint: use conditional statements)
for i in range(11):
    if i % 2 == 0 and i != 0:
        print(f"\t{i}")


All 1 - 10:
	0
	1
	2
	3
	4
	5
	6
	7
	8
	9
	10

Even 1 - 10:
	2
	4
	6
	8
	10


### WHILE Loop  
With the while loop we can execute a set of statements as long as a condition is true.

In [48]:
# while example
i = 1
while i < 12:
  print(i)
  i += 1 # i = i + 1   

1
2
3
4
5
6
7
8
9
10
11


In [49]:
# break the loop based on a condition
i = 1
while i < 12:
  print(i)
  if i == 7:
    break
  i += 1

1
2
3
4
5
6
7


In [50]:
# break the loop based on a condition
#-=1 is typically used to indicate that a value is being decremented by 1.
i = 1
while i < 12:
  print(i)
  if i == -7:
    break
  i -= 1

1
0
-1
-2
-3
-4
-5
-6
-7


In [51]:
# continue the loop based on a condition
i = 0
while i < 6:
  i += 1
  if i == 2:
    continue
  print(i)

1
3
4
5
6


In [86]:
#### ADD YOUR CODE HERE

# Write a WHILE loop to print every number 0-10
i: int = 0
while i <= 10:
    print(i)
    i += 1

print("\n")
# Write a WHILE loop to print every even number 0-10 using BREAK or CONTINUE
i: int = -1
while i <= 10:
    i += 1
    if not (i % 2 == 0 and i != 0):
        continue
    print(i)

0
1
2
3
4
5
6
7
8
9
10


2
4
6
8
10


### Functions
Functions are very useful for *readability* and *replicability* of our code. They allow us to set aside a section of code that we want to use more than once, so that we do not have to type it out multiple times - thus reducing the total length of our code.

A function is built with a `def` keyword, a function name, and arguments in parentheses. Arguments may not be necesary for a function, but the parenteses are! Functions are called using the function name and, depending on the function, arguments.

It is good practice to set the data type for your arguments and to have a description of the function in block quotes (`''' '''`).

For example, we below we have a function to calculate the square of a number.

In [53]:
# def funtion_name(argument=datatype):
#   ''' Doc string '''
#   BODY OF CODE
#   return(OUTPUT)

def square_int(num:int):
    '''
        Returns the square of an integer.
    '''
    square = num * num
    return square

In [54]:
# test our function
n = square_int(2)
print(f'the square of 2 is {n}')

the square of 2 is 4


In [88]:
#### ADD YOUR CODE HERE
from typing import Optional, Union
from dataclasses import dataclass

@dataclass
class Triangle:  # right
    a: Optional[int] = None
    b: Optional[int] = None
    c: Optional[int] = None

    def __init__(self, a = None, b = None, c = None):
        self.a = a
        self.b = b
        self.c = c
        self.__postinit__()

    def __postinit__(self):
        none_vals = 0
        if self.a is None:
            none_vals += 1
        if self.b is None:
            none_vals += 1
        if self.c is None:
            none_vals += 1
        if none_vals > 1:
            raise RuntimeError(f"Must have at least two sides. Got {3 - none_vals} sides.")
        
    def run(self) -> Union[int, float]:
        self.__postinit__()
        if self.a is not None and self.b is not None:
            self.c = np.sqrt((self.a ** 2) + (self.b ** 2))
            return self.c
        elif self.a is not None and self.c is not None:
            self.b = np.sqrt((self.c ** 2) - (self.a ** 2))
            return self.b
        else:
            self.a = np.sqrt((self.c ** 2) - (self.b ** 2))
            return self.a
# Write a function that calculates the third side of a triangle
# (hint: you will need to import the math module)

def calculate_third_side(a = None, b = None, c = None) -> Union[int, float]:
    triangle = Triangle(a, b, c)
    return triangle.run()

print(calculate_third_side(4, 4))


5.656854249492381


### Enumerate function  
Very useful but not that famous like other built in functions in python.  
This function allows us to loop through something and have an automatic counter.  
  
For instance, let's say we have a list of CSV files that we need to loop through. We need to extract the CSV filename and use a counter to loop through the list. 


In [56]:
lst = ['project_out.csv','spectral_reflectance.csv','model_1_result.csv','final_dataframe.csv']

for counter, csv_file in enumerate(lst):
    print(counter, csv_file)

0 project_out.csv
1 spectral_reflectance.csv
2 model_1_result.csv
3 final_dataframe.csv


# DOWNLODING MODULES/ Packages

In [57]:
!pip install datetime
!pip install pandas

# Importing Modules

In [58]:
# Importing the math module
import math


#some helper functions
# dir(math)
# #help(math)
# help(math.sqrt)

# Using math functions
print("Square root of 16 is:", math.sqrt(16))
print("Pi value is:", math.pi)

import datetime

# Getting the current date and time
now = datetime.datetime.now()
print("Current date and time:", now)

# Formatting the date
formatted_date = now.strftime("%Y-%m-%d %H:%M:%S")
print("Formatted date:", formatted_date)

# Parsing a date string
date_str = "2024-08-16"
parsed_date = datetime.datetime.strptime(date_str, "%Y-%m-%d")
print("Parsed date:", parsed_date)

Square root of 16 is: 4.0
Pi value is: 3.141592653589793
Current date and time: 2024-09-04 13:43:07.695595
Formatted date: 2024-09-04 13:43:07
Parsed date: 2024-08-16 00:00:00


# Basic File Handling

In [59]:
# Writing to a file
with open("example.txt", "w") as my_file:
    my_file.write("Hello, World!")

# Reading from a file
with open("example.txt", "r") as my_file:
    content = my_file.read()
    print(content)


# write info in text file

a=[1,2,3,4,5,6,7]

with open("myinfo.txt", "w") as my_file:
    my_file.write(str(a))

Hello, World!
